name: "Create Documentation"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: sphinx-apidoc -f -o docs/source/modules rl_tools/
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"